title: Tales from the Field
author: Steve Tran
email: stran@redhat.com
description: This is a collection of random thoughts
github_username: sqtran
linkedin_username: steve-tran-a9a30331

markdown: kramdown
theme: jekyll-theme-leap-day
